// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Site struct {
	ID     int32  `json:"id"`
	Domain string `json:"domain"`
	Token  string `json:"token"`
}
