// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Branch struct {
	Domain     string    `json:"domain"`
	Branch     string    `json:"branch"`
	LastUpdate time.Time `json:"last_update"`
	Enable     bool      `json:"enable"`
	Archive    string    `json:"archive"`
}

type Site struct {
	Domain string `json:"domain"`
	Token  string `json:"token"`
}
