// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Site struct {
	ID     int32  `json:"id"`
	Slug   string `json:"slug"`
	Domain string `json:"domain"`
	Token  string `json:"token"`
	Enable bool   `json:"enable"`
}
